# Generated by Django 4.0.4 on 2022-04-14 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addressbook_app', '0003_sqllogin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email_id',
        ),
    ]
